remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Steps in Recipes vs Taste Triumph
description: Investigating the Influence of Number of Steps on the Average Rating of a Recipe
